# Generated by Django 3.2.16 on 2022-10-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coef',
            options={'managed': True, 'ordering': ['id']},
        ),
    ]
