# Generated by Django 3.2.16 on 2022-11-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coef',
        ),
        migrations.DeleteModel(
            name='Losses',
        ),
        migrations.DeleteModel(
            name='MolMass',
        ),
    ]
