# Generated by Django 3.2.16 on 2022-10-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20221019_0929'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='p10protokolkgn',
            table='p10_protocol_kgn',
        ),
    ]
