# Generated by Django 3.2.16 on 2022-10-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_p10protokolkgn_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondensateprodOne',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('v_op', models.FloatField()),
                ('mk_ic5', models.FloatField()),
                ('xkprod_ic5', models.FloatField()),
                ('mk_nc5', models.FloatField()),
                ('xkprod_nc5', models.FloatField()),
                ('mk_c6', models.FloatField()),
                ('xkprod_c6', models.FloatField()),
                ('vk_st_y', models.FloatField()),
                ('pk_op', models.FloatField()),
                ('application', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'condensateprod_one',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondensateprodThree1',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('month', models.FloatField()),
                ('day', models.FloatField()),
                ('hour', models.FloatField()),
            ],
            options={
                'db_table': 'condensateprod_three1',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondensateprodThree2',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('q_sh', models.FloatField()),
                ('gk', models.FloatField()),
                ('tau', models.FloatField()),
                ('p_opk', models.FloatField()),
            ],
            options={
                'db_table': 'condensateprod_three2',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondensateprodTwo',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('trial', models.CharField(max_length=255)),
                ('v_pr', models.FloatField()),
                ('p', models.FloatField()),
                ('n', models.FloatField()),
                ('b_pr', models.FloatField()),
                ('xk_prod', models.FloatField()),
                ('p_opk', models.FloatField()),
            ],
            options={
                'db_table': 'condensateprod_two',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondrecyclingEight',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=255)),
                ('pt_p', models.FloatField()),
                ('mp', models.FloatField()),
                ('r', models.FloatField()),
                ('tr_p', models.FloatField()),
                ('pnj', models.FloatField()),
                ('v_ychij', models.FloatField()),
                ('pr_z_ij', models.FloatField()),
                ('v_ych_ij', models.FloatField()),
                ('pkj', models.FloatField()),
                ('days', models.FloatField()),
                ('pr_op_ij', models.FloatField()),
                ('np_t_ij', models.FloatField()),
                ('pyp', models.FloatField()),
            ],
            options={
                'db_table': 'condrecycling_eight',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondrecyclingFive',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('a_ij', models.FloatField()),
                ('b_ij', models.FloatField()),
                ('tau_ij', models.FloatField()),
                ('aa_ij', models.FloatField()),
                ('p_yp', models.FloatField()),
            ],
            options={
                'db_table': 'condrecycling_five',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondrecyclingFour',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(max_length=255)),
                ('v_pr', models.FloatField()),
                ('p', models.FloatField()),
                ('n', models.FloatField()),
                ('b_pn', models.FloatField()),
                ('p_opk', models.FloatField()),
            ],
            options={
                'db_table': 'condrecycling_four',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondrecyclingNine',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=255)),
                ('gm_o', models.FloatField()),
                ('nt', models.FloatField()),
                ('nk', models.FloatField()),
                ('pr_a', models.FloatField()),
            ],
            options={
                'db_table': 'condrecycling_nine',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondrecyclingOne',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(max_length=255)),
                ('gr_o', models.FloatField()),
                ('nst_v', models.FloatField()),
                ('tau', models.FloatField()),
                ('vs_p', models.FloatField()),
                ('ss_p', models.FloatField()),
                ('ps_p', models.FloatField()),
            ],
            options={
                'db_table': 'condrecycling_one',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondrecyclingSeven',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('heat_con', models.CharField(max_length=255)),
                ('p_ed', models.FloatField()),
                ('nt_o', models.FloatField()),
                ('tau_p', models.FloatField()),
                ('p_t_o', models.FloatField()),
            ],
            options={
                'db_table': 'condrecycling_seven',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondrecyclingThree',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('batch_num', models.CharField(max_length=255)),
                ('pg_p', models.FloatField()),
                ('mp', models.FloatField()),
                ('r', models.FloatField()),
                ('tg_p', models.FloatField()),
                ('ppj', models.FloatField()),
                ('v_o', models.FloatField()),
                ('v_pol', models.FloatField()),
                ('n', models.FloatField()),
                ('kf', models.FloatField()),
                ('v', models.FloatField()),
                ('py_s', models.FloatField()),
                ('pa', models.FloatField()),
                ('pb_d', models.FloatField()),
            ],
            options={
                'db_table': 'condrecycling_three',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondrecyclingTwo',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('batch_num', models.CharField(max_length=255)),
                ('hr', models.FloatField()),
                ('ppj', models.FloatField()),
                ('py_s', models.FloatField()),
                ('d', models.FloatField()),
                ('kn', models.FloatField()),
                ('ko', models.FloatField()),
                ('p', models.FloatField()),
                ('tau', models.FloatField()),
                ('tau_g', models.FloatField()),
                ('pm_d', models.FloatField()),
            ],
            options={
                'db_table': 'condrecycling_two',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondrecyclingTwoDop',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('max_first', models.FloatField()),
                ('level_first', models.FloatField()),
                ('hr', models.FloatField()),
            ],
            options={
                'db_table': 'condrecycling_two_dop',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondrecyclingTwoDop2',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('max_first', models.FloatField()),
                ('level_first', models.FloatField()),
                ('hr', models.FloatField()),
            ],
            options={
                'db_table': 'condrecycling_two_dop2',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
