# Generated by Django 3.2.16 on 2022-11-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_rtp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoefPTM',
        ),
        migrations.DeleteModel(
            name='P2Calc',
        ),
        migrations.DeleteModel(
            name='P3Calc',
        ),
        migrations.DeleteModel(
            name='P4Calc',
        ),
        migrations.DeleteModel(
            name='P5Calc',
        ),
        migrations.DeleteModel(
            name='P6Calc',
        ),
        migrations.DeleteModel(
            name='P7Calc',
        ),
        migrations.DeleteModel(
            name='TabCoefAll',
        ),
        migrations.DeleteModel(
            name='TabSumAll',
        ),
        migrations.DeleteModel(
            name='TotalCalc',
        ),
    ]
