# Generated by Django 3.2.16 on 2022-11-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calc_losses',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=255)),
                ('p_ap_avg', models.FloatField()),
                ('k_d_avg', models.FloatField()),
                ('pa_sh_sum', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'calc_losses',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Losses_gas_apparatus',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('device', models.CharField(max_length=255)),
                ('p_ap', models.FloatField()),
                ('t_ap', models.FloatField()),
                ('v_ap', models.FloatField()),
                ('tay_ap', models.FloatField()),
                ('k_d', models.FloatField()),
                ('n_ap', models.FloatField()),
                ('pa_sh', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'losses_gas_apparatus',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
