# Generated by Django 3.2.16 on 2022-11-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoefPTM',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('p', models.FloatField()),
                ('t', models.FloatField()),
                ('m', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'coef_p_t_m',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P2Calc',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('d_e', models.FloatField()),
                ('molar', models.FloatField()),
                ('p', models.FloatField()),
                ('t', models.FloatField()),
                ('m', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'p2_calc',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P3Calc',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('d_e', models.FloatField()),
                ('molar', models.FloatField()),
                ('p', models.FloatField()),
                ('t', models.FloatField()),
                ('m', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'p3_calc',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P4Calc',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('d_e', models.FloatField()),
                ('molar', models.FloatField()),
                ('p', models.FloatField()),
                ('t', models.FloatField()),
                ('m', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'p4_calc',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P5Calc',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('d_e', models.FloatField()),
                ('molar', models.FloatField()),
                ('p', models.FloatField()),
                ('t', models.FloatField()),
                ('m', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'p5_calc',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P6Calc',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('d_e', models.FloatField()),
                ('molar', models.FloatField()),
                ('p', models.FloatField()),
                ('t', models.FloatField()),
                ('m', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'p6_calc',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='P7Calc',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('d_e', models.FloatField()),
                ('molar', models.FloatField()),
                ('p', models.FloatField()),
                ('t', models.FloatField()),
                ('m', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'p7_calc',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabCoefAll',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('p_pl', models.FloatField()),
                ('t_pl', models.FloatField()),
                ('p_kr', models.FloatField()),
                ('t_kr', models.FloatField()),
                ('p_pl_sm', models.FloatField()),
                ('p_pr', models.FloatField()),
                ('t_pr', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'tab_coef_all',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabSumAll',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sum_d_e', models.FloatField()),
                ('sum_mol', models.FloatField()),
                ('sum_p', models.FloatField()),
                ('sum_t', models.FloatField()),
                ('sum_m', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'tab_sum_all',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalCalc',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scalc_one', models.FloatField()),
                ('calc_two', models.FloatField()),
                ('calc_threе', models.FloatField()),
                ('calc_four', models.FloatField()),
                ('zn', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'total_calc',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
