# Generated by Django 3.2.16 on 2022-12-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0002_mer_per_month_ser_per_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sen_equip',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('r1', models.FloatField()),
                ('r2', models.FloatField()),
                ('r3', models.FloatField()),
                ('r4', models.FloatField()),
                ('r5', models.FloatField()),
                ('r6', models.FloatField()),
                ('r7', models.FloatField()),
                ('r8', models.FloatField()),
                ('r9', models.FloatField()),
                ('r10', models.FloatField()),
                ('r11', models.FloatField()),
                ('r12', models.FloatField()),
                ('dy13', models.FloatField()),
                ('rt13', models.FloatField()),
                ('dy14', models.FloatField()),
                ('rt14', models.FloatField()),
                ('dy15', models.FloatField()),
                ('rt15', models.FloatField()),
                ('dy16', models.FloatField()),
                ('rt16', models.FloatField()),
                ('r17', models.FloatField()),
                ('r18', models.FloatField()),
                ('r19', models.FloatField()),
                ('r20', models.FloatField()),
                ('r21', models.FloatField()),
                ('r22', models.FloatField()),
                ('r23', models.FloatField()),
                ('r24', models.FloatField()),
                ('r25', models.FloatField()),
                ('r26', models.FloatField()),
                ('r27', models.FloatField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'sen_equip',
                'ordering': ['update_time'],
                'managed': False,
            },
        ),
    ]
