# Generated by Django 3.2.16 on 2022-12-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0004_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ser_per_day',
            options={'managed': False},
        ),
    ]
