# Generated by Django 3.2.16 on 2022-12-14 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0005_alter_ser_per_day_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sen_equip',
            options={'managed': False, 'ordering': ['date_update']},
        ),
    ]
