# Generated by Django 3.2.16 on 2022-12-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0006_alter_sen_equip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'managed': False, 'ordering': ['date_update']},
        ),
    ]
