# Generated by Django 3.2.16 on 2022-11-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_rmo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perehod_stabilizacii',
            table='perehod_stabilizacii',
        ),
    ]
