# Generated by Django 3.2.16 on 2022-11-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_rmo', '0002_alter_perehod_stabilizacii_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Losses_gas',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('update_date', models.DateTimeField()),
                ('fakel', models.FloatField()),
                ('recicling', models.FloatField()),
            ],
            options={
                'db_table': 'losses_gas',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meters_data_20e_1',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('update_date', models.DateTimeField()),
                ('_20e_1_1', models.FloatField()),
                ('_20e_1_2', models.FloatField()),
                ('_20e_1_3', models.FloatField()),
                ('itog', models.FloatField()),
            ],
            options={
                'db_table': 'meters_data_20e_1',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='P5_app',
        ),
        migrations.DeleteModel(
            name='P6_app',
        ),
    ]
